services:
  zipkin:
    image: 'openzipkin/zipkin:2.23'
    ports:
      - '9411:9411'
	  
  naming-server:
    image: 'clarkesw/naming-server:0.0.4-SNAPSHOT'
    mem_limit: 700m
    ports:
      - '8761:8761'